require "./cli_help"
require "./cli_args_validation"

# Generates shell completion for the suite's own CLI grammar:
#
#   bin [options] <task> [flags] [key=value] [~exclusions] [@ <task> ...]
#
# Everything the script offers comes from the registries the binary runs on --
# CLIHelp's visible tasks and the #2423 argument allowlists -- so completion,
# help and validation cannot drift apart. The bash function is plain enough to
# run under zsh's bashcompinit as well, which is how the zsh variant works.
module CLICompletion
  SHELLS        = ["bash", "zsh"]
  DEFAULT_SHELL = "bash"
  FUNCTION_NAME = "_cnf_testsuite_completions"

  # Named arguments whose value is a path, completed with file names.
  FILE_VALUED_ARGS = CLIOptions.visible.select(&.file).map(&.name)

  def self.script(shell : String, bin_name : String = self.bin_name) : String
    case shell
    when "bash" then bash_script(bin_name)
    when "zsh"  then zsh_script(bin_name)
    else raise ArgumentError.new("unsupported shell #{shell}")
    end
  end

  # The binary the script is generated by is the one it should complete: the
  # release binary is `cnf-testsuite`, a shards build may be named differently.
  def self.bin_name : String
    name = Process.executable_path.try { |path| File.basename(path) }
    return CLIHelp::BIN_NAME if name.nil? || name.starts_with?("crystal-run")
    name
  end

  def self.task_paths : Array(String)
    CLIHelp.visible_tasks.map(&.path).sort
  end

  def self.log_levels : Array(String)
    Log::Severity.values.reject(&.none?).map(&.to_s.downcase)
  end

  private def self.zsh_script(bin_name : String) : String
    <<-ZSH
    # zsh completion for #{bin_name} -- generated by `#{bin_name} completion zsh`.
    # Install with: source <(#{bin_name} completion zsh)
    autoload -U +X compinit && compinit
    autoload -U +X bashcompinit && bashcompinit

    #{bash_script(bin_name)}
    ZSH
  end

  private def self.bash_script(bin_name : String) : String
    <<-BASH
    # bash completion for #{bin_name} -- generated by `#{bin_name} completion bash`.
    # Install with: source <(#{bin_name} completion bash)
    # Remove with:  complete -r #{bin_name}
    #{FUNCTION_NAME}() {
      local tasks="#{task_paths.join(" ")}"
      local flags="#{CLIOptions.visible.select(&.kind.flag?).map(&.long).join(" ")}"
      local valued="#{CLIOptions.visible.select(&.takes_value?).map(&.long).join(" ")}"
      local file_args=" #{FILE_VALUED_ARGS.map { |arg| "--#{arg}" }.join(" ")} "
      local task_args=" #{CLIOptions.multis.map(&.long).join(" ")} "
      local levels="#{log_levels.join(" ")}"
      local options="-l --loglevel -h --help --version $flags $valued"

      # Take the word under the cursor from the raw line rather than COMP_WORDS:
      # bash splits words on ':' and '=' (COMP_WORDBREAKS), which would cut
      # setup:install_kubescape and cnf-config=path apart.
      local line="${COMP_LINE:0:$COMP_POINT}"
      local cur="${line##*[[:space:]]}"
      local before="${line:0:${#line}-${#cur}}"

      # Walk the completed words to learn what the cursor position expects:
      # the value of the option just before it, a help topic, a shell name, or
      # - the default - a task name or an option.
      local state="task" expect="" w
      local -a cwords=()
      for w in $before; do cwords+=("$w"); done
      local i=1
      while (( i < ${#cwords[@]} )); do
        w="${cwords[i]}"
        if [[ -n "$expect" ]]; then
          expect=""
        elif [[ "$w" == "-l" || "$w" == "--loglevel" ]]; then
          expect="level"
        elif [[ "$task_args" == *" $w "* ]]; then
          expect="task"
        elif [[ "$file_args" == *" $w "* ]]; then
          expect="file"
        elif [[ "$w" == --* && "$valued" == *" $w "* ]]; then
          expect="value"
        elif [[ "$state" == "task" && "$w" != -* ]]; then
          case "$w" in
            help)       state="help" ;;
            completion) state="shell" ;;
            *)          state="args" ;;
          esac
        elif [[ "$state" == "help" || "$state" == "shell" ]]; then
          state="done"
        fi
        (( i++ ))
      done

      local -a candidates=() reply=()
      local prefix="" value="$cur" f
      # --option=value completes like the value after `--option `.
      if [[ -z "$expect" && "$cur" == --*=* ]]; then
        w="${cur%%=*}"; value="${cur#*=}"; prefix="$w="
        if [[ "$task_args" == *" $w "* ]]; then expect="task"
        elif [[ "$file_args" == *" $w "* ]]; then expect="file"
        elif [[ "$valued" == *" $w "* ]]; then expect="value"; fi
      fi
      case "$expect" in
        level) candidates=($levels) ;;
        task)  candidates=($tasks) ;;
        file)
          # A plain glob rather than compgen -f: under zsh's bashcompinit
          # compgen ignores its word and globs the completion prefix instead.
          for f in "$value"*; do
            [[ -e "$f" ]] || continue
            [[ -d "$f" ]] && f="$f/"
            candidates+=("$f")
          done ;;
        value) ;;
        *)
          case "$state" in
            help)  candidates=(tasks $tasks) ;;
            shell) candidates=(#{SHELLS.join(" ")}) ;;
            done)  ;;
            *)
              if [[ "$cur" == -* ]]; then candidates=($options); else candidates=($tasks); fi ;;
          esac ;;
      esac
      if [[ -n "$prefix" ]]; then
        local -a prefixed=()
        for w in "${candidates[@]}"; do prefixed+=("$prefix$w"); done
        candidates=("${prefixed[@]}")
      fi

      # Prefix test by substring rather than a glob pattern: zsh's sh emulation
      # does not always treat a quoted "$cur"* as literal text.
      for w in "${candidates[@]}"; do
        [[ "${w:0:${#cur}}" == "$cur" ]] && reply+=("$w")
      done

      # bash replaces only the text after the last ':' or '=' it split on; hand
      # back that part. Only for the characters actually in COMP_WORDBREAKS.
      local breaks="${COMP_WORDBREAKS//[^:=]/}"
      if [[ -n "$breaks" && "$cur" == *["$breaks"]* ]]; then
        local head="${cur%[$breaks]*}"
        head="${cur:0:${#head}+1}"
        reply=("${reply[@]#"$head"}")
      fi

      # A lone `dir/` completion continues on the same word.
      if [[ ${#reply[@]} -eq 1 && "${reply[0]}" == */ ]]; then
        type compopt &>/dev/null && compopt -o nospace 2>/dev/null
      fi
      COMPREPLY=("${reply[@]}")
    }
    complete -F #{FUNCTION_NAME} #{bin_name}
    BASH
  end
end
