apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deprecated-ingress
  annotations:
    # Deprecated in v1.32
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: "lfnetworking.org"
