# renovate: datasource=docker depName=cr.fluentbit.io/fluent/fluent-bit
image:
  repository: fluent/fluent-bit
  tag: 5.1.1
  digest: sha256:a941bdd5ca552b2c6597fc7b3bccf2e61d30873939bab5700963de0e94ac6169
config:
  outputs: |
    [OUTPUT]
        Name file
        Format template
        Path /testdata
