---
apiVersion: v1
kind: Namespace
metadata:
  name: cnfspace
  labels:
    pod-security.kubernetes.io/enforce: privileged

---
apiVersion: v1
kind: Pod
metadata:
  name: stuck-pod
  namespace: cnfspace
  finalizers:
    - example.com/stuck
  labels:
    app: stuck-app
spec:
  containers:
  - name: stuck-container
    image: busybox
    command: ["sh", "-c", "while true; do sleep 3600; done"]